Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Uses AWS credentials on machine
fs = s3fs.S3FileSystem() 

# which data bucket?
bucket = 'snowex-data'  
      
# contents inside /depths     
flist = fs.ls(f'{bucket}/tutorial-data/core-datasets/depths') 

# show list of files
print('File list is: ', flist)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mClientError[0m                               Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py[0m in [0;36m_lsdir[0;34m(self, path, refresh, max_items, delimiter, prefix)[0m
[1;32m    571[0m                 [0mdircache[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 572[0;31m                 [0;32masync[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mit[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    573[0m                     [0mdircache[0m[0;34m.[0m[0mextend[0m[0;34m([0m[0mi[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"CommonPrefixes"[0m[0;34m,[0m [0;34m[[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/paginate.py[0m in [0;36m__anext__[0;34m(self)[0m
[1;32m     31[0m         [0;32mwhile[0m [0;32mTrue[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 32[0;31m             [0mresponse[0m [0;34m=[0m [0;32mawait[0m [0mself[0m[0;34m.[0m[0m_make_request[0m[0;34m([0m[0mcurrent_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     33[0m             [0mparsed[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_extract_parsed_response[0m[0;34m([0m[0mresponse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/client.py[0m in [0;36m_make_api_call[0;34m(self, operation_name, api_params)[0m
[1;32m    153[0m             [0merror_class[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexceptions[0m[0;34m.[0m[0mfrom_code[0m[0;34m([0m[0merror_code[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 154[0;31m             [0;32mraise[0m [0merror_class[0m[0;34m([0m[0mparsed_response[0m[0;34m,[0m [0moperation_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    155[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mClientError[0m: An error occurred (ExpiredToken) when calling the ListObjectsV2 operation: The provided token has expired.

The above exception was the direct cause of the following exception:

[0;31mPermissionError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-4-bd2b8bcf9659>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0;31m# contents inside /depths[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mflist[0m [0;34m=[0m [0mfs[0m[0;34m.[0m[0mls[0m[0;34m([0m[0;34mf'{bucket}/tutorial-data/core-datasets/depths'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m [0;31m# show list of files[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m     85[0m     [0;32mdef[0m [0mwrapper[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     86[0m         [0mself[0m [0;34m=[0m [0mobj[0m [0;32mor[0m [0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 87[0;31m         [0;32mreturn[0m [0msync[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mloop[0m[0;34m,[0m [0mfunc[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     88[0m [0;34m[0m[0m
[1;32m     89[0m     [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py[0m in [0;36msync[0;34m(loop, func, timeout, *args, **kwargs)[0m
[1;32m     66[0m         [0;32mraise[0m [0mFSTimeoutError[0m[0;34m[0m[0;34m[0m[0m
[1;32m     67[0m     [0;32mif[0m [0misinstance[0m[0;34m([0m[0mresult[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mBaseException[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 68[0;31m         [0;32mraise[0m [0mresult[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     69[0m     [0;32mreturn[0m [0mresult[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     70[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py[0m in [0;36m_runner[0;34m(event, coro, result, timeout)[0m
[1;32m     22[0m         [0mcoro[0m [0;34m=[0m [0masyncio[0m[0;34m.[0m[0mwait_for[0m[0;34m([0m[0mcoro[0m[0;34m,[0m [0mtimeout[0m[0;34m=[0m[0mtimeout[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     23[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 24[0;31m         [0mresult[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m=[0m [0;32mawait[0m [0mcoro[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     25[0m     [0;32mexcept[0m [0mException[0m [0;32mas[0m [0mex[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m         [0mresult[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m=[0m [0mex[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py[0m in [0;36m_ls[0;34m(self, path, detail, refresh)[0m
[1;32m    775[0m             [0mfiles[0m [0;34m=[0m [0;32mawait[0m [0mself[0m[0;34m.[0m[0m_lsbuckets[0m[0;34m([0m[0mrefresh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    776[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 777[0;31m             [0mfiles[0m [0;34m=[0m [0;32mawait[0m [0mself[0m[0;34m.[0m[0m_lsdir[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mrefresh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    778[0m             [0;32mif[0m [0;32mnot[0m [0mfiles[0m [0;32mand[0m [0;34m"/"[0m [0;32min[0m [0mpath[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    779[0m                 [0mfiles[0m [0;34m=[0m [0;32mawait[0m [0mself[0m[0;34m.[0m[0m_lsdir[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_parent[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m,[0m [0mrefresh[0m[0;34m=[0m[0mrefresh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py[0m in [0;36m_lsdir[0;34m(self, path, refresh, max_items, delimiter, prefix)[0m
[1;32m    593[0m                     [0mf[0m[0;34m[[0m[0;34m"name"[0m[0;34m][0m [0;34m=[0m [0mf[0m[0;34m[[0m[0;34m"Key"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    594[0m             [0;32mexcept[0m [0mClientError[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 595[0;31m                 [0;32mraise[0m [0mtranslate_boto_error[0m[0;34m([0m[0me[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    596[0m [0;34m[0m[0m
[1;32m    597[0m             [0;32mif[0m [0mdelimiter[0m [0;32mand[0m [0mfiles[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mPermissionError[0m: The provided token has expired.
PermissionError: The provided token has expired.

