Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from sliderule import icesat2

# initialize
icesat2.init("icesat2sliderule.org", verbose=False)

# region of interest polygon
region = [ {"lon":lon_i, "lat":lat_i} for lon_i, lat_i in 
          zip(np.array(lonlims)[[0, -1, -1, 0, 0]],  np.array(latlims)[[0, 0, -1, -1, 0]])]

# request parameters
params = {
    "poly": region,  # request the polygon defined by our lat-lon bounds
    "srt": icesat2.SRT_LAND, # request classification based on the land algorithm
    "cnf": icesat2.CNF_SURFACE_MEDIUM, # use all photons of low confidence or better
    "len": 20.0,  # fit data in overlapping 40-meter segments
    "res": 10.0,  # report one height every 20 m
    "ats":5., #report a segment only if it contains at least 2 photons separated by 5 m
    "maxi": 6,  # allow up to six iterations in fitting each segment to the data
}

# make request
rsps = icesat2.atl06p(params, "atlas-s3")

# save the result in a dataframe
df = pd.DataFrame(rsps)

# calculate the polar-stereographic coordinates:
df['x'], df['y']=to_image_crs.transform(df['lat'], df['lon'])

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTimeoutError[0m                              Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connection.py[0m in [0;36m_new_conn[0;34m(self)[0m
[1;32m    168[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 169[0;31m             conn = connection.create_connection(
[0m[1;32m    170[0m                 [0;34m([0m[0mself[0m[0;34m.[0m[0m_dns_host[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mport[0m[0;34m)[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mtimeout[0m[0;34m,[0m [0;34m**[0m[0mextra_kw[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/util/connection.py[0m in [0;36mcreate_connection[0;34m(address, timeout, source_address, socket_options)[0m
[1;32m     95[0m     [0;32mif[0m [0merr[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 96[0;31m         [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     97[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/util/connection.py[0m in [0;36mcreate_connection[0;34m(address, timeout, source_address, socket_options)[0m
[1;32m     85[0m                 [0msock[0m[0;34m.[0m[0mbind[0m[0;34m([0m[0msource_address[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 86[0;31m             [0msock[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0msa[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     87[0m             [0;32mreturn[0m [0msock[0m[0;34m[0m[0;34m[0m[0m

[0;31mTimeoutError[0m: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

[0;31mNewConnectionError[0m                        Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connectionpool.py[0m in [0;36murlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)[0m
[1;32m    698[0m             [0;31m# Make the request on the httplib connection object.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 699[0;31m             httplib_response = self._make_request(
[0m[1;32m    700[0m                 [0mconn[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connectionpool.py[0m in [0;36m_make_request[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)[0m
[1;32m    393[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 394[0;31m                 [0mconn[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mmethod[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0;34m**[0m[0mhttplib_request_kw[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    395[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connection.py[0m in [0;36mrequest[0;34m(self, method, url, body, headers)[0m
[1;32m    233[0m             [0mheaders[0m[0;34m[[0m[0;34m"User-Agent"[0m[0;34m][0m [0;34m=[0m [0m_get_default_user_agent[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 234[0;31m         [0msuper[0m[0;34m([0m[0mHTTPConnection[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mmethod[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0mbody[0m[0;34m=[0m[0mbody[0m[0;34m,[0m [0mheaders[0m[0;34m=[0m[0mheaders[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    235[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/http/client.py[0m in [0;36mrequest[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1254[0m         [0;34m"""Send a complete request to the server."""[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1255[0;31m         [0mself[0m[0;34m.[0m[0m_send_request[0m[0;34m([0m[0mmethod[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0mbody[0m[0;34m,[0m [0mheaders[0m[0;34m,[0m [0mencode_chunked[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1256[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/http/client.py[0m in [0;36m_send_request[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1300[0m             [0mbody[0m [0;34m=[0m [0m_encode[0m[0;34m([0m[0mbody[0m[0;34m,[0m [0;34m'body'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1301[0;31m         [0mself[0m[0;34m.[0m[0mendheaders[0m[0;34m([0m[0mbody[0m[0;34m,[0m [0mencode_chunked[0m[0;34m=[0m[0mencode_chunked[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1302[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/http/client.py[0m in [0;36mendheaders[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1249[0m             [0;32mraise[0m [0mCannotSendHeader[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1250[0;31m         [0mself[0m[0;34m.[0m[0m_send_output[0m[0;34m([0m[0mmessage_body[0m[0;34m,[0m [0mencode_chunked[0m[0;34m=[0m[0mencode_chunked[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1251[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/http/client.py[0m in [0;36m_send_output[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1009[0m         [0;32mdel[0m [0mself[0m[0;34m.[0m[0m_buffer[0m[0;34m[[0m[0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1010[0;31m         [0mself[0m[0;34m.[0m[0msend[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1011[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/http/client.py[0m in [0;36msend[0;34m(self, data)[0m
[1;32m    949[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0mauto_open[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 950[0;31m                 [0mself[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    951[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connection.py[0m in [0;36mconnect[0;34m(self)[0m
[1;32m    199[0m     [0;32mdef[0m [0mconnect[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 200[0;31m         [0mconn[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_new_conn[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    201[0m         [0mself[0m[0;34m.[0m[0m_prepare_conn[0m[0;34m([0m[0mconn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connection.py[0m in [0;36m_new_conn[0;34m(self)[0m
[1;32m    180[0m         [0;32mexcept[0m [0mSocketError[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 181[0;31m             raise NewConnectionError(
[0m[1;32m    182[0m                 [0mself[0m[0;34m,[0m [0;34m"Failed to establish a new connection: %s"[0m [0;34m%[0m [0me[0m[0;34m[0m[0;34m[0m[0m

[0;31mNewConnectionError[0m: <urllib3.connection.HTTPConnection object at 0x7f7d257dbe80>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

[0;31mMaxRetryError[0m                             Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/adapters.py[0m in [0;36msend[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    438[0m             [0;32mif[0m [0;32mnot[0m [0mchunked[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 439[0;31m                 resp = conn.urlopen(
[0m[1;32m    440[0m                     [0mmethod[0m[0;34m=[0m[0mrequest[0m[0;34m.[0m[0mmethod[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/connectionpool.py[0m in [0;36murlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)[0m
[1;32m    754[0m [0;34m[0m[0m
[0;32m--> 755[0;31m             retries = retries.increment(
[0m[1;32m    756[0m                 [0mmethod[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0merror[0m[0;34m=[0m[0me[0m[0;34m,[0m [0m_pool[0m[0;34m=[0m[0mself[0m[0;34m,[0m [0m_stacktrace[0m[0;34m=[0m[0msys[0m[0;34m.[0m[0mexc_info[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/urllib3/util/retry.py[0m in [0;36mincrement[0;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[1;32m    572[0m         [0;32mif[0m [0mnew_retry[0m[0;34m.[0m[0mis_exhausted[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 573[0;31m             [0;32mraise[0m [0mMaxRetryError[0m[0;34m([0m[0m_pool[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0merror[0m [0;32mor[0m [0mResponseError[0m[0;34m([0m[0mcause[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    574[0m [0;34m[0m[0m

[0;31mMaxRetryError[0m: HTTPConnectionPool(host='34.216.150.33', port=9081): Max retries exceeded with url: /source/atl06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d257dbe80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

[0;31mConnectionError[0m                           Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/sliderule.py[0m in [0;36msource[0;34m(api, parm, stream, callbacks)[0m
[1;32m    375[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 376[0;31m                 [0mdata[0m [0;34m=[0m [0mrequests[0m[0;34m.[0m[0mpost[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mrqst[0m[0;34m,[0m [0mstream[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    377[0m                 [0mrsps[0m [0;34m=[0m [0m__parse[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mcallbacks[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/api.py[0m in [0;36mpost[0;34m(url, data, json, **kwargs)[0m
[1;32m    118[0m [0;34m[0m[0m
[0;32m--> 119[0;31m     [0;32mreturn[0m [0mrequest[0m[0;34m([0m[0;34m'post'[0m[0;34m,[0m [0murl[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdata[0m[0;34m,[0m [0mjson[0m[0;34m=[0m[0mjson[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    120[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/api.py[0m in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     60[0m     [0;32mwith[0m [0msessions[0m[0;34m.[0m[0mSession[0m[0;34m([0m[0;34m)[0m [0;32mas[0m [0msession[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 61[0;31m         [0;32mreturn[0m [0msession[0m[0;34m.[0m[0mrequest[0m[0;34m([0m[0mmethod[0m[0;34m=[0m[0mmethod[0m[0;34m,[0m [0murl[0m[0;34m=[0m[0murl[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     62[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/sessions.py[0m in [0;36mrequest[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    541[0m         [0msend_kwargs[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0msettings[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 542[0;31m         [0mresp[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0msend[0m[0;34m([0m[0mprep[0m[0;34m,[0m [0;34m**[0m[0msend_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    543[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/sessions.py[0m in [0;36msend[0;34m(self, request, **kwargs)[0m
[1;32m    654[0m         [0;31m# Send the request[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 655[0;31m         [0mr[0m [0;34m=[0m [0madapter[0m[0;34m.[0m[0msend[0m[0;34m([0m[0mrequest[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    656[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/requests/adapters.py[0m in [0;36msend[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    515[0m [0;34m[0m[0m
[0;32m--> 516[0;31m             [0;32mraise[0m [0mConnectionError[0m[0;34m([0m[0me[0m[0;34m,[0m [0mrequest[0m[0;34m=[0m[0mrequest[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    517[0m [0;34m[0m[0m

[0;31mConnectionError[0m: HTTPConnectionPool(host='34.216.150.33', port=9081): Max retries exceeded with url: /source/atl06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d257dbe80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-19-edcf675b8119>[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m [0;31m# make request[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m [0mrsps[0m [0;34m=[0m [0micesat2[0m[0;34m.[0m[0matl06p[0m[0;34m([0m[0mparams[0m[0;34m,[0m [0;34m"atlas-s3"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     24[0m [0;34m[0m[0m
[1;32m     25[0m [0;31m# save the result in a dataframe[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/icesat2.py[0m in [0;36matl06p[0;34m(parm, asset, track, as_numpy, max_workers, block)[0m
[1;32m    476[0m     [0mresources[0m [0;34m=[0m [0m__query_resources[0m[0;34m([0m[0mparm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    477[0m     [0mmax_workers[0m [0;34m=[0m [0m__query_servers[0m[0;34m([0m[0mmax_workers[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 478[0;31m     [0;32mreturn[0m [0m__parallelize[0m[0;34m([0m[0matl06[0m[0;34m,[0m [0mparm[0m[0;34m,[0m [0mresources[0m[0;34m,[0m [0mmax_workers[0m[0;34m,[0m [0mblock[0m[0;34m,[0m [0masset[0m[0;34m,[0m [0mtrack[0m[0;34m,[0m [0mas_numpy[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    479[0m [0;34m[0m[0m
[1;32m    480[0m [0;31m#[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/icesat2.py[0m in [0;36m__parallelize[0;34m(function, parm, resources, max_workers, block, *args)[0m
[1;32m    333[0m                     [0mresults[0m [0;34m=[0m [0mfuture[0m[0;34m.[0m[0mresult[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    334[0m                 [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 335[0;31m                     [0mresult[0m [0;34m=[0m [0mfuture[0m[0;34m.[0m[0mresult[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    336[0m                     [0;32mfor[0m [0melement[0m [0;32min[0m [0mresult[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    337[0m                         [0;32mif[0m [0melement[0m [0;32mnot[0m [0;32min[0m [0mresults[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py[0m in [0;36mresult[0;34m(self, timeout)[0m
[1;32m    430[0m                 [0;32mraise[0m [0mCancelledError[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    431[0m             [0;32melif[0m [0mself[0m[0;34m.[0m[0m_state[0m [0;34m==[0m [0mFINISHED[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 432[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__get_result[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    433[0m [0;34m[0m[0m
[1;32m    434[0m             [0mself[0m[0;34m.[0m[0m_condition[0m[0;34m.[0m[0mwait[0m[0;34m([0m[0mtimeout[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py[0m in [0;36m__get_result[0;34m(self)[0m
[1;32m    386[0m     [0;32mdef[0m [0m__get_result[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    387[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0m_exception[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 388[0;31m             [0;32mraise[0m [0mself[0m[0;34m.[0m[0m_exception[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    389[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    390[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_result[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/thread.py[0m in [0;36mrun[0;34m(self)[0m
[1;32m     55[0m [0;34m[0m[0m
[1;32m     56[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 57[0;31m             [0mresult[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mfn[0m[0;34m([0m[0;34m*[0m[0mself[0m[0;34m.[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mself[0m[0;34m.[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     58[0m         [0;32mexcept[0m [0mBaseException[0m [0;32mas[0m [0mexc[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     59[0m             [0mself[0m[0;34m.[0m[0mfuture[0m[0;34m.[0m[0mset_exception[0m[0;34m([0m[0mexc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/icesat2.py[0m in [0;36matl06[0;34m(parm, resource, asset, track, as_numpy)[0m
[1;32m    451[0m [0;34m[0m[0m
[1;32m    452[0m     [0;31m# Execute ATL06 Algorithm[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 453[0;31m     [0mrsps[0m [0;34m=[0m [0msliderule[0m[0;34m.[0m[0msource[0m[0;34m([0m[0;34m"atl06"[0m[0;34m,[0m [0mrqst[0m[0;34m,[0m [0mstream[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    454[0m [0;34m[0m[0m
[1;32m    455[0m     [0;31m# Flatten Responses[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/sliderule.py[0m in [0;36msource[0;34m(api, parm, stream, callbacks)[0m
[1;32m    380[0m         [0;32mexcept[0m [0mException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    381[0m             [0mlogger[0m[0;34m.[0m[0mcritical[0m[0;34m([0m[0me[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 382[0;31m             [0m__errserv[0m[0;34m([0m[0mserv[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    383[0m     [0;32mreturn[0m [0mrsps[0m[0;34m[0m[0;34m[0m[0m
[1;32m    384[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/sliderule/sliderule.py[0m in [0;36m__errserv[0;34m(serv)[0m
[1;32m    164[0m     [0;32mglobal[0m [0mserver_table[0m[0;34m,[0m [0mserver_max_errors[0m[0;34m[0m[0;34m[0m[0m
[1;32m    165[0m     [0;32mwith[0m [0mserver_lock[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 166[0;31m         [0mserver_table[0m[0;34m[[0m[0mserv[0m[0;34m][0m [0;34m+=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    167[0m         [0mlogger[0m[0;34m.[0m[0mcritical[0m[0;34m([0m[0mserv[0m [0;34m+[0m [0;34m" encountered consecutive error "[0m [0;34m+[0m [0mstr[0m[0;34m([0m[0mserver_table[0m[0;34m[[0m[0mserv[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    168[0m         [0;32mif[0m [0mserver_table[0m[0;34m[[0m[0mserv[0m[0;34m][0m [0;34m>[0m [0mserver_max_errors[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'http://34.216.150.33:9081'
KeyError: 'http://34.216.150.33:9081'

